services:
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Next.js
      - "3902:3902"  # WebSocket/API Server
    env_file:
      - ./dashboard/.env
    environment:
      - NODE_ENV=development
      - PORT=3902
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_SERVICE_SID=${TWILIO_SERVICE_SID}
      - PII_REDACTION_ENABLED=${PII_REDACTION_ENABLED}
      - PUBLIC_URL=${PUBLIC_URL}
    volumes:
      - ./dashboard:/app
      - /app/node_modules
      - /app/.next
      - /app/dist
    command: npm run dev  # Override production CMD for development
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
